---
title: "Date Conversion Code"
author: "Data Analyst Moses Kioko"
date: "3/19/2020"
output: html_document
---

**Libraries**
```{r message=FALSE, warning=FALSE}
library(lubridate) #dates conversion package
library(DT) #table package
library(rio)
install_formats()
```


**Import Data**
```{r message=FALSE, warning=FALSE}
data<-import("E:\\New folder\\data.xlsx")

#subset the data
date_unconverted<-data[1:3]
```

**Structure of the Data**
```{r}
str(date_unconverted)

DT::datatable(date_unconverted,class = 'cell-border stripe',rownames = F,caption = "Table 1: Un-converted Dates",options = list(columnDefs = list(list(className = 'dt-center', targets = 0:2))))
```

**Convert the Dates** 
```{r message=FALSE, warning=FALSE}

dates<-data[1:3]

dates$SubmissionDate<-date(dates$SubmissionDate)
dates$starttime<-date(dates$starttime)
dates$endtime<-date(dates$endtime)
```
**Converted Dates Output**
```{r}
datatable(dates,class = 'cell-border stripe',rownames = F,caption = "Table 2: Converted Dates",options = list(columnDefs = list(list(className = 'dt-center', targets = 0:2))))
```



